global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 0.1 # tune if map update loop missed its desired rate
   publish_frequency: 0.1
   transform_tolerance: 0.5

# uncomment to remove the need for an a priori map
#   plugins: []

   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

